@Library("jenlib") _

Map<String, Object> pipelineOptions = [
		projects: ["model-hw-mc-genetic"],
		container: [app: "dls"],
		notificationChannel: "#jjk-notifications",
		configureInstallOptions: "--build-profile=ci",
		moduleOptions: [modules: ["ppu-toolchain"]],
		testSlurmResource: [partition: "cube", wafer: 62, "fpga-without-aout": 3],
		preTestHook: { configureHxCubeBitfile() },
		testOptions: "--test-execall -j1"
]

withCcache() {
	wafDefaultPipeline(pipelineOptions)
}
